In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5])

In [6]:
b = np.array((6, 7, 8, 9, 10))

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
print(b)

[ 6  7  8  9 10]


In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [10]:
c = a + b

In [11]:
print(c)

[ 7  9 11 13 15]


In [14]:
d = np.array([1, 2, 3, 4, 5],dtype="f")

In [15]:
print(d)

[1. 2. 3. 4. 5.]


In [16]:
print(type(d))

<class 'numpy.ndarray'>


In [18]:
d.dtype

dtype('float32')