# NumPy practice

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.round(10*np.random.rand(2,3))

In [4]:
a

array([[5., 3., 0.],
       [7., 2., 9.]])

In [5]:
b = np.arange(2)

In [6]:
b

array([0, 1])

In [11]:
b = np.arange(2).reshape(2, 1)

In [9]:
b

array([[0],
       [1]])

In [12]:
a+b

array([[ 5.,  3.,  0.],
       [ 8.,  3., 10.]])

In [15]:
c = np.round(10*np.random.rand(2, 2))

In [16]:
c

array([[1., 7.],
       [2., 1.]])

In [19]:
d = np.hstack((a,c))

In [20]:
d

array([[5., 3., 0., 1., 7.],
       [7., 2., 9., 2., 1.]])

In [21]:
A = np.random.permutation(np.arange(10))

In [22]:
A

array([4, 5, 3, 6, 9, 1, 0, 7, 8, 2])

In [23]:
A1 = np.arange(10)

In [24]:
A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
A2 = np.random.permutation(10)

In [26]:
A2

array([4, 9, 7, 8, 5, 6, 0, 3, 1, 2])

In [27]:
type(A2)

numpy.ndarray

In [28]:
type(A1)

numpy.ndarray

In [29]:
type(A)

numpy.ndarray

In [30]:
A2.sort()

In [31]:
A2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.sort(A2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
k = map(str, input().split())

ajsdfkj al; asdlkfj asldkjf 


In [44]:
k = list(k)

In [45]:
g = np.array(k)

In [46]:
g

array(['ajsdfkj', 'al;', 'asdlkfj', 'asldkjf'], dtype='<U7')

In [47]:
print(g)

['ajsdfkj' 'al;' 'asdlkfj' 'asldkjf']


In [48]:
g.sort()

In [49]:
print(g)

['ajsdfkj' 'al;' 'asdlkfj' 'asldkjf']
